Update dependencies
capacitor-community/intercom pull request #113
Opened 2024-11-01 08:49 UTC by jpike88

2024-11-01 15:12 UTC, stewones commented
hey @jpike88 can yo check these conflicts?

2024-11-01 23:07 UTC, jcesarmobile requested changes
This PR breaks build, lint and fmt npm scripts.
Also breaks the iOS build because Intercom 18 requires iOS 15 but the plugin supports iOS 13+.
Updating the Android dependencies is a breaking change, doesn't break the build, but should be taken into consideration for doing a major version bump if this PR gets merged.

2024-11-02 01:14 UTC, stewones commented
good catch, thanks for checking @jcesarmobile 
consumers can always override the version in their client, so do we really want these changes in the first place?

2024-11-04 05:48 UTC, jpike88 commented
I've fixed and addressed all above concerns I could find, thoughts?

2024-11-05 05:43 UTC, jpike88 commented
I forked and tested on both android and iOS, seems fine

2024-11-23 14:20 UTC, stewones commented
could you take a peak @jcesarmobile ?

2025-01-20 06:21 UTC, jpike88 commented
Two months later............

2025-02-02 18:50 UTC, stewones commented
> Two months later............

sorry for delay @jpike88 but unfortunately that's how open source works.
can you please rebase again? I promise to try and have a look this week

thank you.

2025-02-03 02:39 UTC, jpike88 commented
resolved conflict, ready to look at

2025-02-04 20:19 UTC, stewones commented
LGTM thanks @jpike88

2025-02-04 20:19 UTC, merged